# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfa9bf66a6ac9394b127f7926dd26bde853df1150fa7406a01549bc5865e07a0325ad51432a78dd20e934745e413e2e47741371e1951017617d2caa9f567d85f

test:
  secret_key_base: c64afbe326189c664df6baec2c1c89ed928e891da98845302293fe33ac9a3d7fcad87e2dd745454a1bfe2784f03215a78e8209051cd7b637cc000913cfe9f841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
